export const cdx_config = {
  bgColorPrimary: '#7553BB',
  bgColorSecondary: 'white',
  borderPrimary: '2px solid #7553BB',
  borderSecondary: '2px solid #7553BB',
  colorPrimary: 'white',
  colorSecondary: '#7553BB',
  colorPlaceholder: 'lightgray',
  colorAlpha: 'rgba(117, 83, 187, 0.5)',
  fontSizeLabel: '1.5rem',
  fontSizeText: '1.2rem',
  borderRadius: '1rem',
  boxShadow: 'none',
  padding: '1rem 2rem',
  margin: '1rem',
  transformScale: '1',
  transitionTime: '0.3s',
  label: 'Label',
  gap: '1.5rem',
  labelFontWeight: '500',
  colorPrimaryDiff: '#210c4d',
  scrollbarWidth: '17px',
  DDDcolor: '#5a33ab',
};
